Repository canonical/canonicalwebteam.discourse, pull requests merged in 2019-04, with the labels that each got.

#1 Create extension
  .circleci/config.yml
  .gitignore
  LICENSE
  canonicalwebteam/__init__.py
  canonicalwebteam/discourse_docs/__init__.py
  canonicalwebteam/discourse_docs/app.py
  canonicalwebteam/discourse_docs/blueprint.py
  canonicalwebteam/discourse_docs/models.py
  renovate.json
  setup.py
  tests/__init__.py
  tests/fixtures/__init__.py
  tests/fixtures/snapcraft_forum_mock.py
  tests/test_models.py
Labels: Review: Code needed, Review: QA needed

#2 Update readme
  README.md
  setup.py
Labels: Review: Code +1

#4 Restructure
  .gitignore
  CHANGES.txt
  README.md
  canonicalwebteam/discourse_docs/app.py
  canonicalwebteam/discourse_docs/blueprint.py
  canonicalwebteam/discourse_docs/exceptions.py
  canonicalwebteam/discourse_docs/models.py
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
  tests/fixtures/forum_mock.py
  tests/fixtures/snapcraft_forum_mock.py
  tests/fixtures/templates/document.html
  tests/test_app.py
  tests/test_models.py
Labels: Review: Code +1, Review: QA +1
