Repository canonical/canonicalwebteam.discourse, pull requests merged in 2020-12, with the labels that each got.

#65 Fix the get started example to include all modules
  README.md
Labels: Review: Code +1

#66 Add release-drafter action for Discourse module
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/tests.yml
Labels: Review: Code +1

#67 Rename DocParser to TutorialParser
  README.md
  canonicalwebteam/discourse/__init__.py
  canonicalwebteam/discourse/app.py
  canonicalwebteam/discourse/parsers/__init__.py
  canonicalwebteam/discourse/parsers/base_parser.py
  canonicalwebteam/discourse/parsers/tutorials_parser.py
  setup.py
  tests/test_app.py
Labels: Review: Code +1

#68 Added new docs parser
  canonicalwebteam/discourse/__init__.py
  canonicalwebteam/discourse/app.py
  canonicalwebteam/discourse/parsers/__init__.py
  canonicalwebteam/discourse/parsers/base_parser.py
  canonicalwebteam/discourse/parsers/docs.py
  canonicalwebteam/discourse/parsers/engage.py
  canonicalwebteam/discourse/parsers/tutorials.py
  canonicalwebteam/discourse/parsers/tutorials_parser.py
Labels: Review: Code +1, Review: QA +1

#70 Parse version table
  .github/workflows/tests.yml
  canonicalwebteam/discourse/app.py
  canonicalwebteam/discourse/parsers/base_parser.py
  canonicalwebteam/discourse/parsers/docs.py
  canonicalwebteam/discourse/parsers/engage.py
  canonicalwebteam/discourse/parsers/tutorials.py
Labels: Review: Code +1, Review: QA +1

#71 Release V3
  .github/workflows/tests.yml
  README.md
  canonicalwebteam/discourse/__init__.py
  canonicalwebteam/discourse/app.py
  canonicalwebteam/discourse/parsers/__init__.py
  canonicalwebteam/discourse/parsers/base_parser.py
  canonicalwebteam/discourse/parsers/docs.py
  canonicalwebteam/discourse/parsers/docs_parser.py
  canonicalwebteam/discourse/parsers/engage.py
  canonicalwebteam/discourse/parsers/tutorials.py
  setup.py
  tests/test_app.py
Labels: Review: Code +1, Review: QA +1

#72 Support for levels 1 from the beginning
  canonicalwebteam/discourse/parsers/docs.py
  setup.py
Labels: Review: Code needed
