Repository canonical/canonicalwebteam.discourse, pull requests merged in 2020-02, with the labels that each got.

#31 Fix check if value is undefined
  CHANGES.txt
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
Labels: Review: Code +1

#28 Update DocParser
  README.md
Labels: Review: Code needed

#30 Replace polls from discourse.
  CHANGES.txt
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
Labels: Review: QA +1

#33 Fix AttributeError in some docs
  CHANGES.txt
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
Labels: Review: Code +1, Review: QA +1
