Repository canonical/canonicalwebteam.discourse, pull requests merged in 2020-01, with the labels that each got.

#19 Add sections to context
  CHANGES.txt
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
Labels: Review: Code +1, Review: QA +1

#20 Add remaning duration
  .python-version
  canonicalwebteam/discourse_docs/parsers.py
Labels: Review: QA +1

#21 Add metadata parsing
  canonicalwebteam/discourse_docs/app.py
  canonicalwebteam/discourse_docs/parsers.py
Labels: Review: Code +1, Review: QA +1

#22 Bump to version v0.8.0
  CHANGES.txt
  setup.py
Labels: Review: Code +1

#23 Set commit id for GH Action
  .github/workflows/publish.yml
Labels: Review: Code +1

#24 Fix parsing duration
  CHANGES.txt
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
Labels: Review: Code +1, Review: QA +1

#25 Parse categories api to get correct urls
  CHANGES.txt
  canonicalwebteam/discourse_docs/app.py
  canonicalwebteam/discourse_docs/models.py
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
  tests/fixtures/forum_mock.py
  tests/test_app.py
Labels: Review: Code +1, Review: QA +1

#26 Remove image wrapper
  CHANGES.txt
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
Labels: Review: Code +1, Review: QA +1

#27 Add try expect for categories
  CHANGES.txt
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
Labels: Review: Code +1, Review: QA +1

#29 Fix slug issue wit non alpha num char
  CHANGES.txt
  canonicalwebteam/discourse_docs/parsers.py
  setup.py
Labels: Review: Code +1, Review: QA +1
